
version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../asm/backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ..
      dockerfile: ./asm/frontend/Dockerfile
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - backend